version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: Scripts/installnode.sh
      runas: root
  AfterInstall:
    - location: Scripts/startnode.sh
      runas: root
artifacts:
  paths: 
    - /
